### PR TITLE
chore: updated dep and auditing fixes

### PR DESCRIPTION
**Pull request by anikethsaha**
closes #889 #888 

Updated dep and auditing

### CODE REVIEW

**Comment by anikethsaha** [comment]
as `cssnano-utils` is not published as of now, I am getting package not found for cssnano plugins.
Should I link all using `yarn link` and then proceed with upgrading each ?

**Comment by evilebottnawi** [comment]
Yes

**Comment by anikethsaha** [comment]
@evilebottnawi I couldnt able to upgrade the dep of packages which had `cssnano-utils` as dep even after running `lerna link` !

any suggestions ?

**Comment by evilebottnawi** [comment]
> got the same error as package not found

We need publish package, feel free to do it and add me as admin to npm

**Comment by anikethsaha** [comment]
> > got the same error as package not found
> 
> We need publish package, feel free to do it and add me as admin to npm

ok I will publish that and then will update this PR

**Pull request merged**
