### PR TITLE
Use PostCSS 7

### LINKED ISSUE #587: Postcss 7
Postcss 7 has been released. It would be great if cssnano could support it.

### PR DESCRIPTION
**Pull request by ai**
Fixes #587 

/cc @evilebottnawi

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Looks good, maybe we should also create issue about postcss 7 in plugins what we use

**Comment by ai** [comment]
@evilebottnawi ETA of releasing it?

**Comment by evilebottnawi** [comment]
@ai this week, a lot of work (open source + regular work), sorry

**Comment by radeno** [comment]
Guys It is nice to have postcss 7, but `css-declaration-sorter` still use postcss 6. What about to update it ? Version 4 use postcss 7 also.

**Comment by evilebottnawi** [comment]
@Siilwyn friendly ping

**Comment by radeno** [comment]
@evilebottnawi i meant just update dependency to version 4 :) `cssnano-preset-default` using version 3 (`"css-declaration-sorter": "^3.0.0"`) just change it to ^4.0.0

**Comment by evilebottnawi** [comment]
@radeno oh you are right, please create new issue about this or send a PR

**Comment by radeno** [comment]
@evilebottnawi there are all 3 yarn.lock file outdated.
for cssnano and default and advanced profile. should i commit all of them?

**Pull request merged**
