### PR TITLE
fix: issue#1112

### PR DESCRIPTION
**Pull request by codeonquer**
fix https://github.com/cssnano/cssnano/issues/1112

My idea is:
- find all conflictingProps in firstDecls after prop in intersection
- find conflictingProps in intersection
- they should be the same

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Can you add test case(s)?

**Comment by codeonquer** [comment]
I have added my test case.

My test:

```css
h1{color:#001;color:#002;color:#003}h2{color:#001;color:#002}
```

before:

```css
h1{color:#002;color:#003}h1,h2{color:#001}h2{color:#002}
```

after

```css
h1{color:#001;color:#002;color:#003}h2{color:#001;color:#002}
```

**Comment by codeonquer** [comment]
What should i do next @alexander-akait

**Review by ludofischer — APPROVED** [review]
Although I have never touched this part of the code, I think this is a legitimate fix for a legitimate bug. There are also no changes to the integration test results, so I believe we can safely merge this.

**Comment by ludofischer** [comment]
@codeonquer Thank you for your PR!

**Comment by codeonquer** [comment]
I am glad to contribute to this project! Thank you all @alexander-akait @ludofischer

**Pull request merged**
