### PR TITLE
Postcss normalize casing

### PR DESCRIPTION
**Pull request by YozhikM**
#515 
/cc @evilebottnawi

### CODE REVIEW

**Comment by andyjansson** [comment]
The implementation is a bit narrow and doesn't seem very safe. I'd rather see something written using parsers, doing contextual transformation based on the node type. Scaling this implementation up to that level wouldn't be maintainable and a bit slow.

**Comment by YozhikM** [comment]
@andyjansson I agree, I ran the tests with integration and collected several cases. I'll try the best myself and correct it. If cssnano is not needed in this plugin, I can close PR. What do you think?

**Comment by YozhikM** [comment]
@andyjansson How do you like this?
[link](https://github.com/YozhikM/postcss-normalize-casing/blob/master/lib/index.js)

**Comment by andyjansson** [comment]
At first glance, it's a great improvement. Could you refactor the code to communicate intent a bit better?

**Pull request closed without merging**
