### PR TITLE
feat: update `browserslist` to latest version

### LINKED ISSUE #526: Move to Browserslist 4
The main difference that `browserslist()` now could return `node x.x.x`

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #526

### CODE REVIEW

**Comment by ai** [comment]
Are you ready to find `node x.x.x` in Browserslist results? 😏

**Comment by evilebottnawi** [comment]
@ai hm, what you mean? we just get browsers version in some plugins

**Comment by ai** [comment]
How do you use this browser versions? I think you get some Can I Use data for this versions. You should check that code will not throw a error if Can I Use data will not find browser versions.

**Comment by evilebottnawi** [comment]
@ai can you describe more in detail, I do not understand. Example how we use this https://github.com/cssnano/cssnano/blob/master/packages/postcss-minify-params/src/index.js#L92

**Pull request merged**
