### PR TITLE
Publish

### PR DESCRIPTION
**Pull request by ludofischer**
- css-size@5.0.0
 - cssnano-preset-advanced@5.0.0
 - cssnano-preset-default@5.0.0
 - cssnano-preset-lite@2.0.0
 - cssnano-utils@2.0.0
 - cssnano@5.0.0
 - example-cli-usage@5.0.0
 - postcss-colormin@5.0.0
 - postcss-convert-values@5.0.0
 - postcss-discard-comments@5.0.0
 - postcss-discard-duplicates@5.0.0
 - postcss-discard-empty@5.0.0
 - postcss-discard-overridden@5.0.0
 - postcss-discard-unused@5.0.0
 - postcss-merge-idents@5.0.0
 - postcss-merge-longhand@5.0.0
 - postcss-merge-rules@5.0.0
 - postcss-minify-font-values@5.0.0
 - postcss-minify-gradients@5.0.0
 - postcss-minify-params@5.0.0
 - postcss-minify-selectors@5.0.0
 - postcss-normalize-charset@5.0.0
 - postcss-normalize-display-values@5.0.0
 - postcss-normalize-positions@5.0.0
 - postcss-normalize-repeat-style@5.0.0
 - postcss-normalize-string@5.0.0
 - postcss-normalize-timing-functions@5.0.0
 - postcss-normalize-unicode@5.0.0
 - postcss-normalize-url@5.0.0
 - postcss-normalize-whitespace@5.0.0
 - postcss-ordered-values@5.0.0
 - postcss-reduce-idents@5.0.0
 - postcss-reduce-initial@5.0.0
 - postcss-reduce-transforms@5.0.0
 - postcss-svgo@5.0.0
 - postcss-unique-selectors@5.0.0
 - postcss-zindex@5.0.0
 - stylehacks@5.0.0

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by ludofischer** [comment]
So I am going to publish this on npm as `@latest`, is that fine?

**Comment by alexander-akait** [comment]
@ludofischer I think we need fix one problem https://github.com/cssnano/cssnano/issues/1040, a lot of warnings

**Comment by ludofischer** [comment]
Now that https://github.com/cssnano/cssnano/pull/1043 is merged, shall I bump the version to 5.0.1 and put that as `@latest`?

**Comment by alexander-akait** [comment]
Please use `5.0.0`, it is just fix before publish

**Comment by ludofischer** [comment]
Released it: https://github.com/cssnano/cssnano/releases/tag/cssnano%405.0.0 https://www.npmjs.com/package/cssnano

**Comment by alexander-akait** [comment]
Don't forget remove stale branches :smile: we don't need them

**Comment by alexander-akait** [comment]
@ludofischer we have some money on https://opencollective.com/cssnano and you do big job, you can send invoice and I will approve it for your hard work :heart:

**Pull request merged**
