### PR TITLE
test: multiple slashes on font-name property

### LINKED ISSUE #439: parse font-family name with slash is something wrong?
Hi 
  I have a css font-family rule write use unicode like this

```css
textarea {
  font-family: 'helvetica neue','wenquanyi micro hei','\5FAE\8F6F\96C5\9ED1', '\5B8B\4F53', sans-serif;
}
```
use cssnano compress it . the result  is
```css
textarea{font-family:helvetica neue,wenquanyi micro hei,\\5FAE\8F6F\96C5\9ED1,\\5B8B\4F53,sans-serif}
```

is this wrong or i miss something?

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #439

### CODE REVIEW

**Comment by andyjansson** [comment]
I don't think those tests are right.
https://mothereff.in/font-family#0%5C5FAE%5C8F6F%5C96C5%5C9ED1
https://mothereff.in/font-family#0%5C%5C5B8B%5C%5C4F53

**Comment by evilebottnawi** [comment]
@andyjansson why? we just drop quotes because their two and put one `\`

**Comment by evilebottnawi** [comment]
@andyjansson oh, i see, will fix it in near future

**Comment by evilebottnawi** [comment]
Close in favor, i just add invalid tests, all works fine :+1:

**Pull request closed without merging**
