### PR TITLE
Feature: Support ordering animation values

### LINKED ISSUE #574: Feature: Order animation values
Add support for ordering animation values to `postcss-ordered-values`

Input:
```css
.case-1 {
  animation: linear 1s 2s 3 bounce;
}

.case-2 {
  animation: bounce 3 1s linear 2s;
}
```

Output:
```css
.case-1 {
  animation: bounce 1s linear 2s 3;
}

.case-2 {
  animation: bounce 1s linear 2s 3;
}
```

### PR DESCRIPTION
**Pull request by ben-mckernan**
Resolves #574

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Thanks for PR need update `integrations` tests

**Comment by andyjansson** [comment]
The integration tests in need of being updated are located [here](https://github.com/cssnano/cssnano/tree/master/packages/cssnano-preset-default/src/__tests__/integrations) and [here](https://github.com/cssnano/cssnano/tree/master/packages/cssnano-preset-advanced/src/__tests__/integrations) (one for each preset).

**Comment by ben-mckernan** [comment]
Thanks! I will look into the integration tests.

**Comment by andyjansson** [comment]
Looks good. Thanks!

**Pull request merged**
