### PR TITLE
Migrate to PostCSS 8 but keep multiple AST traversals

### PR DESCRIPTION
**Pull request by ludofischer**
Per our discussion https://github.com/cssnano/cssnano/pull/961, this should supersede #961 and #954 .

I’m exposing cssnano as a plugin that returns a processor, per our disccussion on the postcss repository: https://github.com/postcss/postcss/pull/1485

I think it would be useful to check what the upgrade impact would be on widely used dependents, like: 
* https://github.com/egoist/rollup-plugin-postcss
* https://github.com/webpack-contrib/css-minimizer-webpack-plugin

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Looks good, but why snapshots are changed?

**Comment by ludofischer** [comment]
> Looks good, but why snapshots are changed?

I think the `css-declaration-sorter` update is causing most of the changes. In fact, so far I believe most changes are in `@font-face` delcarations: before `src` came before `font-family` and now it is the inverse.

I have used this command to get the a more precise diff:

```
git diff -U0 --word-diff-regex="[^[:space:]}]+" master packages/cssnano-preset-default/src/__tests__/integrations/
```

**Comment by alexander-akait** [comment]
@ludofischer I am from mobile :disappointed: Can you provide most popular change(s) (couple), just want to ensure we don't break something

**Comment by ludofischer** [comment]
I have made a table with the snapshot changes, grouped per file and preset. It’s either 

1. `@font-face` declaration order change
2. `calc()` gets simplified more
3. some prefixed properties get removed

 I have looked at every diff, but I am not sure I have analysed every change. 

| Sample framework | Default preset change | Advanced preset additional change |
| --- | --- | --- |
| base-v0.1.0.css | `@font-face` declaration order | -webkit-box-sizing and -moz-box-sizing removed |
| basscss-v8.0.2.css | nothing | autoprefixer -webkit-box removed |
| blueprint-v2.4.2.css | nothing | -webkit-box-flex and -ms-flex-preferred-size removed |
| bootstrap-v3.4.0.css | `@font-face` declaration order | -webkit-transition removed |
| bootstrap-v4.2.1.css | nothing | -ms-flex-preferred-size and -ms-flex-positive removed |
| bulma-v0.7.2.css | calc | -webkit-transform removed |
| concise-v4.1.2.css | nothing | -webkit-transition-duration removed |
| foundation-v6.5.3.css | nothing | -webkit-transition removed |
| gumby-v2.6.4.css | `@font-face` declaration order | -webkit-transition removed |
| gutenberg-v0.4.2.css | nothing | -webkit-box-sizing removed |
| hydrogen-v2.2.1.css | nothing | -webkit-box-* properties removed |
| kube-v6.5.2.css | `@font-face` declaration order | nothing |
| milligram-v1.3.0.css | nothing | nothing |
| normalize-v3.0.3.css | nothing | nothing |
| picnic-v6.4.0.css | nothing | -webkit-transform removed |
| schema-v2.0.1.css | nothing | -webkit-transition removed |
| semantic-ui-v2.4.1.css | `@font-face` declaration order | -webkit-inline-box -webkit-transition removed |
| skeleton-v2.0.4.css | nothing | nothing |
| turret-v5.1.3.css | calc | -webkit-box-* removed |
| uikit-v3.0.3.css | nothing | -ms-input-placeholder removed |
| vital-v2.2.1.css | nothing | -ms-appearance-none removed |

### Sample `@font-face` declaration change
Previously the `src` property came first although that did not match the alphabetical order; now it comes in the correct alphabetical order

```css
@font-face{src:url(https://storage.googleapis.com/media.urbit.org/fonts/WorkSans-Thin.ttf) format("truetype");font-family:Work Sans;font-weight:100}
```
becomes
```css
@font-face{font-family:Work Sans;font-weight:100;src:url(https://storage.googleapis.com/media.urbit.org/fonts/WorkSans-Thin.ttf) format("truetype")}
```
### Sample calc change
Resolving `calc()` expressions seems to have become smarter and more expressions are simplified, for example:
```css
padding:calc((1.5rem--2px)/2)
```
becomes

```css
padding:calc(.75rem+1px)
```

**Comment by ludofischer** [comment]
I think cssnano because uses the old PostCSS 7 API, it runs before all other plugins which now use `OnceExit`, so the order is not the same as before. If I use my local PostCSS 8 postcss-calc with `OnceExit()` the result is different again. To preserve the old plugin order we should release postcss-calc with `OnceExit()`: https://github.com/postcss/postcss-calc/pull/125

**Comment by alexander-akait** [comment]
Thanks, so let's publish https://github.com/postcss/postcss-calc/pull/125 firsty?

**Comment by ludofischer** [comment]
> Thanks, so let's publish [postcss/postcss-calc#125](https://github.com/postcss/postcss-calc/pull/125) firsty?

Yes, I think it’s better so just check everything once with all plugins running with PostCSS 8.

**Comment by alexander-akait** [comment]
Can we solve https://github.com/cssnano/cssnano/issues/976 here? Otherwise it will be broken release

**Comment by ludofischer** [comment]
> Can we solve #976 here? Otherwise it will be broken release

Looks like the build config for `preset-lite` needs to become the same as `preset-default`. I’ll take a look at it.

**Comment by alexander-akait** [comment]
@ludofischer Big thanks

**Comment by ludofischer** [comment]
I am not sure I know how to fix #976, I think it’s best to wait for @anikethsaha. 
 Currently in master both `cssnano-preset-default` and `cssnano-preset-lite` depend on `cssnano-utils` `^1.0.0`, but the published `cssnano-preset-default` still depends on `cssnano-util-raw-cache`, so I am not sure the current configuration for `cssnano-preset-default` is correct. 
On top of that I do not understand which is the correct cssnano-utils version to use (after 1.0, cssnano-utils has  published  version 4 and 5, but both are `nightly` and 4 is more recent than 5 https://www.npmjs.com/package/cssnano-utils).
I imagine the exact dependency versions will get updated when running lerna, but `yarn publish` gives an error: 
```
package marked as private, not publishing,
```
 `util/buildMetadata.js` does not work any more as it looks for deleted `metadata.toml` files and I can’t find other instructions to generate the published packages.

**Comment by alexander-akait** [comment]
Oh, I see, again bug in nightly , it should not use latest tag

**Comment by alexander-akait** [comment]
I am really don't have time on this right now :disappointed:

**Comment by anikethsaha** [comment]
Yeah , the GH for nightly has been suspended as it was stale for 2 months.
not really sure how to resume that. 

Also about the cssnano-preset-lite fix, a patch release with correct cssnano-utils version will solve that. 
and if our nightly starts working after some changes in `master`, it would release with all latest.

**Comment by anikethsaha** [comment]
I will try to fix this in this weekend.


Also, huge thanks to @ludofischer for handling this migration. 👍

**Comment by alexander-akait** [comment]
@anikethsaha please try to fix it ASAP, it is big blocker for big work

**Comment by anikethsaha** [comment]
yeah, I will try

**Comment by ludofischer** [comment]
> Also, huge thanks to @ludofischer for handling this migration. +1

Thank you! If you’re reviewing how the build works, maybe you could try to remove your hardcoded credential in `package.json`:

https://github.com/cssnano/cssnano/blob/91604d3ccde260047187dd9cecaaf17ad08f6208/package.json#L17

I don’t know much about publishing to npm, but it seems strange that the process is tied to a specific username (maybe also a very slight security issue?)

**Comment by anikethsaha** [comment]
> > Also, huge thanks to @ludofischer for handling this migration. +1
> 
> Thank you! If you’re reviewing how the build works, maybe you could try to remove your hardcoded credential in `package.json`:
> 
> https://github.com/cssnano/cssnano/blob/91604d3ccde260047187dd9cecaaf17ad08f6208/package.json#L17
> 
> I don’t know much about publishing to npm, but it seems strange that the process is tied to a specific username (maybe also a very slight security issue?)

Yea this is a known concern. apparently, docusaurus + gh pages integration mandates this (not sure about the current version) .

**Comment by alexander-akait** [comment]
Do we need something here before release?

**Comment by anikethsaha** [comment]
I will review this by tomorrow. 

I have enabled the workflow for nightly. there should be a nightly release soon. 


Lets review this PR and merge this change.

**Comment by anikethsaha** [comment]
@ludofischer all plugins are migrated in this PR itself right ? if so lets close the other PR regarding the migration.

**Comment by ludofischer** [comment]
Yes, this pull request should convert all plugins. I’ve rebased on the latest master as there was a conflict in the preset-lite package.json after the latest changes.

**Comment by alexander-akait** [comment]
@ludofischer Big thanks, ready to merge?

**Comment by ludofischer** [comment]
> @ludofischer Big thanks, ready to merge?

Yes

**Comment by alexander-akait** [comment]
Great job, now we need to do release, anybody can help, I am really don't have time on cssnano right now, but I can add permission yo do this

**Comment by anikethsaha** [comment]
I can do by next weekend. 
If anyone has time before that, feel free to do. Need to change the playground code first.

**Comment by alexander-akait** [comment]
@anikethsaha Can you provide link on core what we should change?

**Comment by anikethsaha** [comment]
mentioned here https://github.com/cssnano/cssnano/issues/979#issuecomment-757950692

**Comment by fivethreeo** [comment]
Is this ready for release as-is? If so I can take care of that.

**Comment by stasvas** [comment]
Hi guys, when will there be a new release with PostCSS 8 support? We are looking forward to it! Thanks!

**Comment by Atulin** [comment]
Looks like `5.0.0-rc.0` more-or-less works, but still has issues with the advanced preset:

```
Cannot load preset "advanced". Please check your configuration for errors and try again.
```

and shows an error with the default preset, although it does complete:

```
cssnano-util-raw-cache: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

**Comment by alexander-akait** [comment]
@Atulin you still have old cssnano version

**Comment by alexander-akait** [comment]
Please provide reproducible test repo

**Comment by Atulin** [comment]
`5.0.0-rc.0` is the latest version available on NPM, that's the one I have installed, that's the one I tried to use.

Let's just say I never left that comment and I'll just wait for a full 5.0 release.

**Comment by alexander-akait** [comment]
Can you try to run `npm ls cssnano`?

**Comment by fivethreeo** [comment]
If you use yarn you can add the specific version to resolutions. If you use CssMinimizerPlugin in webpack it will pull in a older cssnano.

**Comment by alexander-akait** [comment]
So how I can reproducible the problem?

**Comment by fivethreeo** [comment]
Make a project with workspaces in yarn. Install cssnano 5.0.0-rc2 in the root and have a workspace under it with a older cssnano. Yarn install, and then run something that needs cssnano in the root.

**Pull request merged**
