### PR TITLE
Add test case that demonstrates a crash with ::slotted + attribute selector

### PR DESCRIPTION
**Pull request by papandreou**
I'm playing around with generating random CSS and stumbled upon a selector that crashes `postcss-minify-selectors`.

### CODE REVIEW

**Comment by anikethsaha** [comment]
Please share some more info

**Comment by papandreou** [comment]
I don't really have any more info. As I said I literally randomly stumbled upon it while playing with generated CSS. The selector appears to be valid according to the [CSS Scoping Module Level 1 WD](https://drafts.csswg.org/css-scoping/#slotted-pseudo)

[The failing CI build](https://dev.azure.com/cssnano/cssnano/_build/results?buildId=392&view=logs&j=c2c677d2-0566-5f84-8e1c-5538035c4fb9&t=9ecd87b9-9728-5bf4-d5d1-fb451260d180&l=490) has the stack trace of the failure:

```

      at packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/container.js:179:31
      at Selector.each (packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/container.js:159:22)
      at Selector.walk (packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/container.js:175:21)
      at packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/container.js:179:31
      at Root.each (packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/container.js:159:22)
      at Root.walk (packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/container.js:175:21)
      at Processor.func (packages/postcss-minify-selectors/src/index.js:192:19)
      at Processor._runSync (packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:84:30)
      at Processor.processSync (packages/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:177:27)
      at getParsed (packages/postcss-minify-selectors/src/index.js:16:27)
      at callback (packages/postcss-minify-selectors/src/index.js:187:33)
      at callback (node_modules/postcss/lib/container.es6:208:18)
      at callback (node_modules/postcss/lib/container.es6:110:18)
      at Root.each (node_modules/postcss/lib/container.es6:76:16)
      at Root.walk (node_modules/postcss/lib/container.es6:107:17)
      at Root.walkRules (node_modules/postcss/lib/container.es6:206:19)
      at plugin (packages/postcss-minify-selectors/src/index.js:169:9)
      at LazyResult.run (node_modules/postcss/lib/lazy-result.es6:352:14)
      at LazyResult.asyncTick (node_modules/postcss/lib/lazy-result.es6:280:26)
      at node_modules/postcss/lib/lazy-result.es6:317:12
      at LazyResult.async (node_modules/postcss/lib/lazy-result.es6:314:23)
      at LazyResult.then (node_modules/postcss/lib/lazy-result.es6:201:17)
      at Object.<anonymous> (util/testHelpers.js:44:37)
```

**Comment by anikethsaha** [comment]
`::slotted([foo|bar])` is an incorrect syntax as inside the `(...)`  because if doesnt support [`universal`](drafts.csswg.org/selectors-4/#the-universal-selector) inside it. 

`foo|bar` is a universal selector 

You can refer more [here](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted)

**Comment by papandreou** [comment]
It does look weird, and I don't claim to understand exactly what the selector means, but isn't it valid per these rules?

```
::slotted( <compound-selector-list> )
<compound-selector-list> = <compound-selector>#
<compound-selector> = [ <type-selector>? <subclass-selector>* [ <pseudo-element-selector> <pseudo-class-selector>* ]* ]!
<subclass-selector> = <id-selector> | <class-selector> | <attribute-selector> | <pseudo-class-selector>
<attribute-selector> = '[' <wq-name> ']' | '[' <wq-name> <attr-matcher> [ <string-token> | <ident-token> ] <attr-modifier>? ']'
<attr-matcher> = [ '~' |  '|'  | '^' | '$' | '*' ]? '='
<wq-name> = <ns-prefix>? <ident-token>
```

One step at a time:

```
::slotted( <compound-selector-list> )
::slotted( <compound-selector># )
::slotted( [ <type-selector>? <subclass-selector>* [ <pseudo-element-selector> <pseudo-class-selector>* ]* ]! )
::slotted( <subclass-selector> )
::slotted( <id-selector> | <class-selector> | <attribute-selector> | <pseudo-class-selector> )
::slotted( <attribute-selector> )
::slotted( '[' <wq-name> ']' | '[' <wq-name> <attr-matcher> [ <string-token> | <ident-token> ] <attr-modifier>? ']' )
::slotted( '[' <wq-name> <attr-matcher> [ <string-token> | <ident-token> ] <attr-modifier>? ']' )
::slotted( '[' <wq-name> '|' [ <string-token> | <ident-token> ] <attr-modifier>? ']' )
::slotted( '[' <wq-name> '|' <ident-token> ']' )
::slotted( '[' <ns-prefix>? <ident-token> '|' <ident-token> ']' )
::slotted( '[' <ident-token> '|' <ident-token> ']' )
::slotted( '[' foo '|' bar ']' )
```

Replacing the literals it becomes `::slotted( [ foo | bar ] )`.

**Comment by evilebottnawi** [comment]
It should be reported to `postcss-selector-parser`, we can't fix it on our side

**Comment by anikethsaha** [comment]
@papandreou thanks for the explanation, yes it does looks like valid syntax.

**Comment by papandreou** [comment]
Thanks! I've reported it here: https://github.com/postcss/postcss-selector-parser/issues/229

**Comment by anikethsaha** [comment]
@papandreou I think it does looks like a valid parsing by the `postcss-selector-parser` as it is [attributes selector and namespace](https://drafts.csswg.org/selectors-4/?expand=1#attrnmsp) which is correctly being parsed by the parser. 

here, the prefix is the namespace and the later is the attribute

`[foo|bar]`

```js
...
nodes: [
    Attribute {
      source: [Object],
      sourceIndex: 0,
      _namespace: 'foo',
      _attribute: 'bar',
      spaces: [Object],
      type: 'attribute',
      raws: {},
      _constructed: true,
      parent: [Circular]
    }
  ],
...
```

I think we need to check for `node.operator` on our end

**Pull request closed without merging**
