### PR TITLE
Remove conversion of `canvastext` to `initial`

### PR DESCRIPTION
**Pull request by krokodok**
Fixes: https://github.com/cssnano/cssnano/issues/1660

### CODE REVIEW

**Comment by ludofischer** [comment]
Hello, thank you for your pull request. I would prefer that we try first to fix it upstream before changing it here. The data in `toInitial.json` is fetched on build from the  [MDN data ](https://github.com/mdn/data) repository. The initial value for color comes from this line in their repository  https://github.com/mdn/data/blob/ab6bf8a2eb9bd8123aa025ba6c8758eaeb0ca2ef/css/properties.json#L4119 . Since you have already researched the spec, would you have time to open an issue or a PR on https://github.com/mdn/data ? You can probably do a better a job of explaining why they should change it than I can, because I am not familiar with this aspect of the spec.

**Comment by ludofischer** [comment]
Currently, it's the color initial value is also canvastext on the MDN website, https://developer.mozilla.org/en-US/docs/Web/CSS/color, so changing it in MDN data would help avoid confusion in the future.

**Comment by krokodok** [comment]
Thank you for your quick reply! I will follow this up over there!

**Comment by krokodok** [comment]
So this seems to be an edge case. It is correct, that `initial` defaults to `canvastext`, but on Chrome there is a browser stylesheet overlay that sets `color` only for `<mark>` elements to `marktext`. I will close this for now and not pursue it further.

**Pull request closed without merging**
