### PR TITLE
fix(cssnano-preset-default): update css-declaration-sorter

### LINKED ISSUE #1514: [Bug]: Sorts animation-longhands before animation-shorthand
### Describe the bug

With `cssDeclarationSorter: true` the new animation longhands `animation-timeline` and `animation-range` are sorted before the `animation` shorthand. As a result, the `animation` shorthand effectively resets the longhand properties. 

### Expected behaviour

I expect longhands to never be moved before shorthands, as this will affect the cascaded properties.

### Steps to reproduce

Transform the following css: 

```css
@keyframes test {
  to {
    opacity: 1;
  }
}

.test {
  animation: test;
  animation-timeline: view();
}
```

It is currently converted to:

```css
@keyframes test{to{opacity:1}}.test{animation-timeline:view();animation:test}
```

The animation-timeline property will then be reset by the `animation` longhand, causing the outputted css to break.

https://cssnano.co/playground/#eyJpbnB1dCI6IkBrZXlmcmFtZXMgdGVzdCB7XG4gIHRvIHtcbiAgICBvcGFjaXR5OiAxO1xuICB9XG59XG5cbi50ZXN0IHtcbiAgYW5pbWF0aW9uOiB0ZXN0O1xuICBhbmltYXRpb24tdGltZWxpbmU6IHZpZXcoKTtcbn0iLCJjb25maWciOiJjc3NuYW5vLXByZXNldC1kZWZhdWx0In0=

### Version

6.0.1

### Preset

default

### Environment

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 251.38 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
```

### Package details

```shell
├─┬ css-loader@6.8.1
│ ├─┬ icss-utils@5.1.0
│ │ └── postcss@8.4.27 deduped
│ ├─┬ postcss-modules-extract-imports@3.0.0
│ │ └── postcss@8.4.27 deduped
│ ├─┬ postcss-modules-local-by-default@4.0.3
│ │ └── postcss@8.4.27 deduped
│ ├─┬ postcss-modules-scope@3.0.0
│ │ └── postcss@8.4.27 deduped
│ ├─┬ postcss-modules-values@4.0.0
│ │ └── postcss@8.4.27 deduped
│ └── postcss@8.4.27
└─┬ css-minimizer-webpack-plugin@5.0.1
  ├─┬ cssnano@6.0.1
  │ ├─┬ cssnano-preset-default@6.0.1
  │ │ ├─┬ css-declaration-sorter@6.4.1
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ cssnano-utils@4.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-calc@9.0.1
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-colormin@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-convert-values@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-discard-comments@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-discard-duplicates@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-discard-empty@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-discard-overridden@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-merge-longhand@6.0.0
  │ │ │ ├── postcss@8.4.27 deduped
  │ │ │ └─┬ stylehacks@6.0.0
  │ │ │   └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-merge-rules@6.0.1
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-minify-font-values@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-minify-gradients@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-minify-params@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-minify-selectors@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-charset@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-display-values@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-positions@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-repeat-style@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-string@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-timing-functions@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-unicode@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-url@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-normalize-whitespace@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-ordered-values@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-reduce-initial@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-reduce-transforms@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-svgo@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ ├─┬ postcss-unique-selectors@6.0.0
  │ │ │ └── postcss@8.4.27 deduped
  │ │ └── postcss@8.4.27 deduped
  │ └── postcss@8.4.27 deduped
  └── postcss@8.4.27 deduped
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Siilwyn**
7.1.0 includes a fix to not change the order of unknown properties to
avoid mixing unknown shorthand and longhand properties.

Closes #1514

Because the snapshots contain some experimental properties which are not included in the sorter I've updated them.

### CODE REVIEW

**Comment by Siilwyn** [comment]
Will fix the TS error soonish, I'll have to publish another version bump.

**Comment by Siilwyn** [comment]
Fixed the regression with commonjs types resolution, ready for review!

**Comment by ludofischer** [comment]
> Fixed the regression with commonjs types resolution, ready for review!

Did you look at the changes in the CSS files to make sure they look as expected? I know it can be quite annoying to inspect those diffs.

**Comment by Siilwyn** [comment]
@ludofischer yes I've looked through them, to be honest there is one unexpected change in blueprint css where `max-width` and `flex-basis` is swapped, I can not reproduce this in a test though.

**Comment by ludofischer** [comment]
> @ludofischer yes I've looked through them, to be honest there is one unexpected change in blueprint css where `max-width` and `flex-basis` is swapped, I can not reproduce this in a test though.
> 

There are other changes I do not understand. For example, why does `font-family` now move before `-ms-size-adjust` (in base-v0.1.0)?

**Comment by Siilwyn** [comment]
@ludofischer sorry for the late reply, I'm back from vacation and took some time to get used to life & work rhythm.

It's an odd change, could it be the combination of other modules causing this?

If I add a test it passes:
```js
test(
  'keep order',
  passthroughCSS('html{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:sans-serif}')
);
```

**Comment by ludofischer** [comment]
It's odd indeed. Do any unwanted consequences come to mind? How could it be other modules if nothing changed in this PR except css-declaration-sorter?

**Comment by ludofischer** [comment]
Hi, I've reapplied the changes myself in a different branch because a SVGO upgrade in-between had caused too many conflicts in the CSS files

**Comment by Siilwyn** [comment]
Ah I see thank you @ludofischer, sorry for not replying been busy again.
:heart:

**Pull request closed without merging**
