### PR TITLE
fix: fix caniuse-api browserslist conflict

### PR DESCRIPTION
**Pull request by ai**
Fixes https://github.com/cssnano/cssnano/issues/537

### CODE REVIEW

**Comment by andyjansson** [comment]
None of the `postcss-reduce-initial` tests seem to be passing with this change.

**Comment by ai** [comment]
Just ESLint warning

**Comment by ai** [comment]
Yeap, we need to move tests from using `env` to `process.env.BROWSERSLIST`, but I don’t know how to do it with metaprogramming.

Somebody need to help me.

**Comment by andyjansson** [comment]
Closing this in favour of #542.

**Pull request closed without merging**
