### PR TITLE
new: cssnano-preset-lite

### PR DESCRIPTION
**Pull request by anikethsaha**
created a new package

`cssnano-preset-lite`

#### Plugins being used

- postcss-normalize-whitespace
- postcss-discard-comments

### CODE REVIEW

**Comment by anikethsaha** [comment]
Merge checklist

- [ ] release the v1 manually
- [ ] update the cssnano-nightly repo

**Comment by evilebottnawi** [comment]
Do you need some help?

**Comment by anikethsaha** [comment]
Not as of now, 

I will update the nightly repo before the nightly release and then I will merge this so that we can get this for the nightly release as well.

**Comment by evilebottnawi** [comment]
Thanks

**Pull request merged**
