### PR TITLE
Unit tests are published to NPM registry

### PR DESCRIPTION
**Pull request by koresar**
See this: https://unpkg.com/browse/postcss-discard-overridden@4.0.1/src/__tests__/

Anything else needed in this PR?

### CODE REVIEW

**Comment by anikethsaha** [comment]
is there any other packages having this same mistake ?

**Comment by koresar** [comment]
From cssnano project? I don't know.

**Comment by koresar** [comment]
I actually checked the source code of about 10 of them. It was good there. I even copied the lines from them for this PR. 😀

**Comment by anikethsaha** [comment]
checking the `package.json.files` should be fine !

**Pull request merged**
