### PR TITLE
chore(deps): update `caniuse-api` to `3.0.0` version

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @ai 

Should we use `ignoreUnkownVersions` in each `browserslist`?

### CODE REVIEW

**Comment by ai** [comment]
Only for tools, where we send `browsers` option (instead of queries).

**Comment by evilebottnawi** [comment]
@ai here `const initialSupport = isSupported('css-initial-value', browsers);`, right?

**Comment by ai** [comment]
Yeap, you need to pass `ignoreUnkownVersions` to `isSupported`

**Comment by evilebottnawi** [comment]
@ai i can't find any docs about this feature in repo :confused:

**Comment by ai** [comment]
They just enable it https://github.com/Nyalab/caniuse-api/blob/master/src/index.js#L47

Not the best way, but whatever :D

**Comment by evilebottnawi** [comment]
@ai i.e. we can merge this and release patch version?

**Comment by ai** [comment]
Yeap, there is no changes, since we didn’t pass queries to `caniuse-api`

**Comment by evilebottnawi** [comment]
Need patch release `postcss-merge-rules` and `postcss-reduce-initial`

@ai @andyjansson 
Should we do patch release `cssnano`?

**Comment by andyjansson** [comment]
>Should we do patch release `cssnano`?

Yes, I believe so. It's not a breaking change or a new feature. A patch is very much appropriate.

**Comment by ai** [comment]
+1 for patch

**Pull request merged**
