### PR TITLE
 Fix leading and trailing whitespaces in grid-template-areas

### LINKED ISSUE #460: Remove leading and trailing spaces in grid area definitions
Input:

```css
foo {
  grid-template-areas: ' foo bar '
                       ' baz qux ';
}
```

Output: `foo{grid-template-areas:' a b ' ' c d '}`

Expected output: `foo{grid-template-areas:'a b' 'c d'}`

Basically, the leading and trailing whitespace inside the quotes is entirely useless, and should be removed.

### PR DESCRIPTION
**Pull request by YozhikM**
Closes #460 
/cc @evilebottnawi

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Thanks for pr i will review in near

**Comment by evilebottnawi** [comment]
@YozhikM can you provide link what is it safe?

**Comment by YozhikM** [comment]
@evilebottnawi  Nothing but [this](https://github.com/postcss/autoprefixer/pull/1018/files/b98948522db78ccf2f5a99425d837c5f4e861664#diff-62fb176577c8305e36ceea69794f5497R41)

**Comment by evilebottnawi** [comment]
@YozhikM why you close PR?

**Comment by YozhikM** [comment]
@evilebottnawi I'm going to open it again without lock files

**Pull request closed without merging**
