### PR TITLE
fix: load time

### LINKED ISSUE #651: Performance: Takes 4-6 seconds to load
I am using cssnano 4.1.4 with gulp (not the gulp plugin) and it's taking ~4seconds to load everytime:

```
console.time("Loading plugins"); // start measuring

const gulp = require('gulp');
const cssnano = require('cssnano');

console.timeEnd('Loading plugins');
```

And the result is usually 4-6seconds: `Loading plugins: 6321.839ms`

This is on MBP Retina with the extremely fast SSDs - it takes even longer on the standard SSDs. I read through the old issues but all I could find was that it'd be fixed in v4 which I'm already using.

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #651

I find a lot of problems with perf, i will try to fix it tomorrow

### CODE REVIEW

**Comment by andyjansson** [comment]
Won't this change cause issues with the test suite by targeting the published version rather than the linked one?

**Comment by evilebottnawi** [comment]
@andyjansson i will tested his manually, you it is decrease loading time, i will search how we can tests this un future

**Pull request merged**
