### PR TITLE
fix: convert value for opacity consistency

### PR DESCRIPTION
**Pull request by anikethsaha**
fix https://github.com/cssnano/cssnano/issues/829

## Summary

- If the opacity value is greater than 1, then fallback to 1
- if the opacity value is greater than 1 and it is a percentage, then keep it as it is

### CODE REVIEW

**Comment by evilebottnawi** [comment]
hm, it is invalid CSS syntax

**Comment by evilebottnawi** [comment]
invalid syntax === invalid minification

**Comment by anikethsaha** [comment]
you meant the `%` is invalid  ?

**Comment by evilebottnawi** [comment]
Yes, try to use this in browser

**Comment by anikethsaha** [comment]
ohh,....I guess it should be then converted into decimal 

`opacity : 40`

⬇️ 

`opacity : 0.4`

**Comment by evilebottnawi** [comment]
@anikethsaha we are not linter or something like what handle incorrect syntax

**Comment by anikethsaha** [comment]
> we are not linter or something like what handle incorrect syntax

😁 yea make sense

👍 closing

I guess good to close #829 too then !

**Comment by interactiveRob** [comment]
Actually percentage is valid syntax and it does work in the browser. Not sure if this has changed somewhat recently. I am running into the same issue on my project using a third-party library that uses % values for opacity. 

https://developer.mozilla.org/en-US/docs/Web/CSS/opacity

**Pull request closed without merging**
